01_StudNet/01_SourceCode/Studnet/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Studnet.Controllers
{
    public class AdminPanelController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(List<string> admins)
        {
            if(admins == null)
            {
                admins = new List<string>();
            }
            var allUsers = AppData.Instance().StudnetDatabase.users;
            bool ifFound = false;
            foreach (var user in allUsers)
            {
                ifFound = false;
                if (user.rank.rank_name.ToLower() != "superadmin")
                {
                    foreach (var newAdmin in admins)
                    {
                        if (newAdmin == user.Id.ToString() && !user.rank.rank_name.ToLower().Contains("admin"))
                        {
                            ifFound = true;
                            AppData.Instance().StudnetDatabase.UserManagement.SetUserRank(user, UserManagement.Rank.Admin);
                        }
                        else if(newAdmin == user.Id.ToString() && user.rank.rank_name.ToLower().Contains("admin"))
                        {
                            ifFound = true;
                        }
                    }
                    if (!ifFound)
                    {
                        if (user.rank.rank_name.ToLower() != "user")
                        {
                            AppData.Instance().StudnetDatabase.UserManagement.SetUserRank(user, UserManagement.Rank.User);
                        }
                    }
                }
            }
            return View();
        }
    }
}

01_StudNet/01_SourceCode/Studnet/Views/AdminPanel/Index.cshtml
@{
    ViewBag.Title = "Panel administratora - zarządzanie użytkownikami";
}

<h2>@ViewBag.Title</h2>

<form method="post">
    @{
        if (ViewBag.Error != null)
        {
            <font color="red"><b>@ViewBag.Error</b></font>
        }
    }
    <table>
        <tr>
            <th scope="col">Imię i nazwisko</th>
            <th scope="col">Administrator</th>
            <th style="padding: 0 0 0 20px" scope="col">Akcja</th>
        </tr>
        
        @foreach (var user in AppData.Instance().StudnetDatabase.users)
        {
            if (user.rank.rank_name.ToLower() != "superadmin")
            {
            <tr>
                <td style="padding: 10px 0">
                    <label for="userId">@user.GetFullName()</label>
                    <input type="hidden" name="userId" value="@user.Id"/>
                </td>
                <td style="padding: 0 0 0 50px">
                    @if (user.rank.rank_name.ToLower().Contains("admin"))
                    {
                        <input type="checkbox" name="admins" value="@user.Id" checked />
                    }
                    else
                    {
                        <input type="checkbox" name="admins" value="@user.Id" />
                    }
                </td>
                <td style="padding: 0 0 0 20px">
                    @Html.ActionLink("Usuń", "RemoveUser", "AdminPanel", new { userId = user.Id }, null)
                </td>
            </tr>
            }
        }
    </table>

    <div class="form-group">
        <input type="submit" class="btn btn-default" value="Zapisz" />
    </div>
</form>