01_StudNet/01_SourceCode/Studnet/Controllers/MainPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Studnet.Controllers.Main
{
    public class MainPageController : Controller
    {
        public AppData AppData
        {
            get
            {
                throw new System.NotImplementedException();
            }

            set
            {
            }
        }

        // GET: Main
        public ActionResult Index()
        {
            AppData.Instance().WebsiteAdress = Request.Url.Host + ":" + Request.Url.Port;
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

01_StudNet/01_SourceCode/Studnet/Controllers/MessageController.cs
using Studnet.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Studnet.Controllers
{
    public class MessageController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            if ((bool)Session["IsLogged"])
            {
                string userMail = Session["User"].ToString();
                users currentUser = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail == userMail).Single();
                List<message> userMessages = currentUser.message.Concat(currentUser.message1).ToList();
                userMessages = userMessages.OrderByDescending(m => m.message_date_created).ToList();
                List<users> conversatedWith = new List<users>();
                foreach (var item in userMessages)
                {
                    conversatedWith.Add(item.users);
                    conversatedWith.Add(item.users1);
                }
                conversatedWith.RemoveAll(m => m.user_mail == userMail);
                conversatedWith = conversatedWith.Distinct().ToList();
                List<message> latestMessages = new List<message>();
                foreach (var user in conversatedWith)
                {
                    latestMessages.Add(userMessages.Where(m => m.users == user || m.users1 == user).First());
                }
                
                ViewBag.CurrentUser = currentUser.Id;
                return View(latestMessages);
            }
            return RedirectToAction("Login", "User");
        }

        [HttpGet]
        public ActionResult Create(int userToId = -1, string preMessage = null)
        {
            if ((bool)Session["IsLogged"])
            {
                string userMail = Session["User"].ToString();
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                if(userToId != -1)
                {
                    ViewBag.UserTo = userToId;
                }
                if(preMessage != null)
                {
                    string fullMessage = "\n\n\n";
                    fullMessage += "------------CYTAT------------\n";
                    fullMessage += preMessage.Trim();
                    ViewBag.PreMessage = fullMessage;
                }
                return View();
            }
            return RedirectToAction("Login", "User");
        }

        [HttpGet]
        public ActionResult Read(int userId)
        {
            List<message> messagesInConv = new List<message>();
            try
            {
                string userMail = Session["User"].ToString();
                users currentUser = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail == userMail).Single();
                users userToRead = AppData.Instance().StudnetDatabase.users.Where(m => m.Id == userId).Single();
                messagesInConv = currentUser.message.Concat(currentUser.message1).Where(m => m.users == userToRead || m.users1 == userToRead).ToList().OrderBy(m => m.message_date_created).ToList();
                ViewBag.ConversationWith = userToRead.GetFullName();
                ViewBag.ConversedWithId = userToRead.Id;
                foreach (var item in messagesInConv)
                {
                    if (item.message_user_to_id == currentUser.Id && !item.message_is_read)
                    {
                        item.message_is_read = true;
                        AppData.Instance().StudnetDatabase.SaveChanges();
                    }
                }
                
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                return RedirectToAction("Index");
            }
            return View(messagesInConv);
        }

        [HttpPost]
        public ActionResult Read(message newMessage)
        {
            newMessage.message_date_created = DateTime.Now;
            string userMail = Session["User"].ToString();
            newMessage.message_user_from_id = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail == userMail).Single().Id;
            newMessage.message_is_read = false;
            users currentUser = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail == userMail).Single();
            users userToRead = AppData.Instance().StudnetDatabase.users.Where(m => m.Id == newMessage.message_user_to_id).Single();
            List<message> messagesInConv = currentUser.message.Concat(currentUser.message1).Where(m => m.users == userToRead || m.users1 == userToRead).ToList().OrderBy(m => m.message_date_created).ToList();
            if (!AppData.Instance().StudnetDatabase.users.Any(m => m.Id == newMessage.message_user_to_id))
            {
                ViewBag.Error = "Niepoprawny odbiorca";
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                ViewBag.ConversationWith = userToRead.GetFullName();
                ViewBag.ConversedWithId = userToRead.Id;
                return View(messagesInConv);
            }
            else if (newMessage.message_user_to_id == newMessage.message_user_from_id)
            {
                ViewBag.Error = "Nie możesz wysłać wiadomości do samego siebie";
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                ViewBag.ConversationWith = userToRead.GetFullName();
                ViewBag.ConversedWithId = userToRead.Id;
                return View(messagesInConv);
            }
            else if (newMessage.message_text == null || newMessage.message_text.Length < 1)
            {
                ViewBag.Error = "Wiadomość nie może być pusta";
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                ViewBag.ConversationWith = userToRead.GetFullName();
                ViewBag.ConversedWithId = userToRead.Id;
                return View(messagesInConv);
            }
            else
            {
                AppData.Instance().StudnetDatabase.MessageManagement.SendMessage(newMessage);
            }

            return RedirectToAction("Read",new { userId = userToRead.Id });
        }

        [HttpPost]
        public ActionResult Create(message newMessage)
        {
            newMessage.message_date_created = DateTime.Now;
            string userMail = Session["User"].ToString();
            newMessage.message_user_from_id = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail == userMail).Single().Id;
            newMessage.message_is_read = false;
            if(!AppData.Instance().StudnetDatabase.users.Any(m=>m.Id == newMessage.message_user_to_id))
            {
                ViewBag.Error = "Niepoprawny odbiorca";
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                return View();
            }
            else if (newMessage.message_user_to_id == newMessage.message_user_from_id)
            {
                ViewBag.Error = "Nie możesz wysłać wiadomości do samego siebie";
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                return View();
            }
            else if(newMessage.message_text == null || newMessage.message_text.Length < 1)
            {
                ViewBag.Error = "Wiadomość nie może być pusta";
                ViewBag.Users = AppData.Instance().StudnetDatabase.users.Where(m => m.user_mail != userMail).ToList();
                return View();
            }
            else
            {
                AppData.Instance().StudnetDatabase.MessageManagement.SendMessage(newMessage);
            }

            return RedirectToAction("Index");
        }
    }
}

01_StudNet/01_SourceCode/Studnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - StudNet</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("StudNet", "Index", "MainPage", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "MainPage")</li>
                    @{
                        if (!(bool)Session["IsLogged"])
                        {
                            <li>@Html.ActionLink("Rejestracja", "Register", "User")</li>
                            <li>@Html.ActionLink("Logowanie", "Login", "User")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Forum", "Index", "Forum")</li>
                            <li>@Html.ActionLink("Kalendarz wydarzeń", "Index", "Event")</li>
                            string userMail = Session["User"].ToString();
                            int userId = AppData.Instance().StudnetDatabase.users.Where(u => u.user_mail == userMail).Single().Id;
                            int newMessages = AppData.Instance().StudnetDatabase.message.Where(m => m.message_user_to_id == userId).Count(m => m.message_is_read == false);
                            if (newMessages > 0)
                            {
                            <li>@Html.ActionLink("Prywatne wiadomości (" + newMessages.ToString() + ")", "Index", "Message")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Prywatne wiadomości", "Index", "Message")</li>
                            }
                            if (Session["Rank"].ToString().ToLower().Contains("admin"))
                            {
                                <li>@Html.ActionLink("Zarządzanie grupami", "Index", "Group")</li>
                            }
                        }
                    }
                </ul>
                @{
                    if ((bool)Session["IsLogged"])
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="False">@Session["Username"]<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Zmień hasło", "ChangePassword", "User")</li>
                                    <li>@Html.ActionLink("Wyloguj", "Logout", "User")</li>
                                </ul>
                            </li>
                        </ul>

                    }
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - StudNet | @Html.ActionLink("O serwisie","About","MainPage")</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>